const fs = require('fs');
const path = require('path');

function parseDotEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const raw = fs.readFileSync(filePath, 'utf8');
  const env = {};

  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;

    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();

    // Remove surrounding quotes if present.
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) fs.mkdirSync(dirPath, { recursive: true });
}

const frontendRoot = path.resolve(__dirname, '..');
const frontendEnvPath = path.resolve(frontendRoot, '.env');
const backendEnvPath = path.resolve(frontendRoot, '..', 'sentimenter', '.env');
const outFile = path.resolve(frontendRoot, 'src', 'assets', 'env.js');

const frontendEnv = parseDotEnv(frontendEnvPath);
const backendEnv = parseDotEnv(backendEnvPath);

const nodeEnv =
  frontendEnv.NODE_ENV ||
  process.env.NODE_ENV ||
  backendEnv.NODE_ENV ||
  '';
const ngAppProduction =
  frontendEnv.NG_APP_PRODUCTION ||
  (nodeEnv === 'production' ? 'true' : '');

// Priority: frontend .env NG_APP_API_URL -> backend .env API_URL -> default.
const frontendApiUrl = frontendEnv.NG_APP_API_URL || '';
const apiUrl = frontendApiUrl || backendEnv.API_URL || '';
const apiBase =
  apiUrl && apiUrl.endsWith('/api') ? apiUrl.replace(/\/api$/, '/api') : apiUrl ? `${apiUrl.replace(/\/$/, '')}/api` : '';

// Fallback to deployed API if env is missing.
const finalApiBase = apiBase || 'https://api.sentimenter.ai/api';

ensureDir(path.dirname(outFile));

const contents = `// AUTO-GENERATED by scripts/generate-env.js
window.__env__ = window.__env__ || {};
window.__env__.NG_APP_API_URL = ${JSON.stringify(finalApiBase)};
window.__env__.NG_APP_PRODUCTION = ${JSON.stringify(ngAppProduction || 'false')};
`;

fs.writeFileSync(outFile, contents, 'utf8');

console.log('[env] generated', path.relative(process.cwd(), outFile));
console.log('[env] NG_APP_API_URL =', finalApiBase);
console.log('[env] NG_APP_PRODUCTION =', ngAppProduction || 'false');

