const fs = require('fs');
const path = require('path');

function parseDotEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const raw = fs.readFileSync(filePath, 'utf8');
  const env = {};

  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;

    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();

    // Remove surrounding quotes if present.
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) fs.mkdirSync(dirPath, { recursive: true });
}

const frontendRoot = path.resolve(__dirname, '..');
const frontendEnvPath = path.resolve(frontendRoot, '.env');
const frontendProductionEnvPath = path.resolve(frontendRoot, '.env.production');
const backendEnvPath = path.resolve(frontendRoot, '..', 'sentimenter', '.env');
const outFile = path.resolve(frontendRoot, 'src', 'assets', 'env.js');

const frontendEnv = parseDotEnv(frontendEnvPath);
const frontendProductionEnv = parseDotEnv(frontendProductionEnvPath);
const backendEnv = parseDotEnv(backendEnvPath);

const nodeEnv =
  process.env.NODE_ENV ||
  frontendProductionEnv.NODE_ENV ||
  frontendEnv.NODE_ENV ||
  backendEnv.NODE_ENV ||
  '';
const isProductionBuild =
  process.argv.includes('--production') ||
  nodeEnv === 'production' ||
  process.env.NG_APP_PRODUCTION === 'true' ||
  frontendProductionEnv.NG_APP_PRODUCTION === 'true' ||
  (process.argv.includes('build') && !process.argv.some((a) => /configuration=development/i.test(a)));

const PRODUCTION_API_DEFAULT = 'https://api.sentimenter.ai/api';

const ngAppProduction =
  frontendProductionEnv.NG_APP_PRODUCTION ||
  (isProductionBuild ? 'true' : '') ||
  frontendEnv.NG_APP_PRODUCTION ||
  process.env.NG_APP_PRODUCTION ||
  'false';

function isRelativeDevApiUrl(url) {
  if (!url) return true;
  const trimmed = String(url).trim();
  return trimmed === '/api' || trimmed.startsWith('/api/');
}

// Priority: .env.production → absolute API URL → backend .env → production default.
const envForApi = isProductionBuild
  ? { ...frontendEnv, ...frontendProductionEnv }
  : frontendEnv;
let frontendApiUrl = envForApi.NG_APP_API_URL || '';
if (isProductionBuild && isRelativeDevApiUrl(frontendApiUrl)) {
  frontendApiUrl =
    frontendProductionEnv.NG_APP_API_URL ||
    backendEnv.API_URL ||
    PRODUCTION_API_DEFAULT;
}
const apiUrl = frontendApiUrl || '';
const apiBase =
  apiUrl && apiUrl.endsWith('/api') ? apiUrl.replace(/\/api$/, '/api') : apiUrl ? `${apiUrl.replace(/\/$/, '')}/api` : '';

// Production must call the API host directly — `/api` only works when nginx proxies on the same origin.
const finalApiBase = apiBase || (isProductionBuild ? PRODUCTION_API_DEFAULT : '/api');

ensureDir(path.dirname(outFile));

const contents = `// AUTO-GENERATED by scripts/generate-env.js
window.__env__ = window.__env__ || {};
window.__env__.NG_APP_API_URL = ${JSON.stringify(finalApiBase)};
window.__env__.NG_APP_PRODUCTION = ${JSON.stringify(ngAppProduction || 'false')};
window.__env__.NG_APP_FIREBASE_API_KEY = ${JSON.stringify(frontendEnv.NG_APP_FIREBASE_API_KEY || '')};
window.__env__.NG_APP_FIREBASE_AUTH_DOMAIN = ${JSON.stringify(frontendEnv.NG_APP_FIREBASE_AUTH_DOMAIN || '')};
window.__env__.NG_APP_FIREBASE_PROJECT_ID = ${JSON.stringify(frontendEnv.NG_APP_FIREBASE_PROJECT_ID || '')};
window.__env__.NG_APP_FIREBASE_STORAGE_BUCKET = ${JSON.stringify(frontendEnv.NG_APP_FIREBASE_STORAGE_BUCKET || '')};
window.__env__.NG_APP_FIREBASE_MESSAGING_SENDER_ID = ${JSON.stringify(frontendEnv.NG_APP_FIREBASE_MESSAGING_SENDER_ID || '')};
window.__env__.NG_APP_FIREBASE_APP_ID = ${JSON.stringify(frontendEnv.NG_APP_FIREBASE_APP_ID || '')};
window.__env__.NG_APP_FIREBASE_VAPID_KEY = ${JSON.stringify(frontendEnv.NG_APP_FIREBASE_VAPID_KEY || '')};
window.__env__.NG_APP_FIREBASE_NOTIFICATIONS_ENABLED = ${JSON.stringify(frontendEnv.NG_APP_FIREBASE_NOTIFICATIONS_ENABLED || 'true')};
`;

fs.writeFileSync(outFile, contents, 'utf8');

console.log('[env] generated', path.relative(process.cwd(), outFile));
console.log('[env] NG_APP_API_URL =', finalApiBase);
console.log('[env] NG_APP_PRODUCTION =', ngAppProduction || 'false');

